export const themes = {
  neon: {
    name: 'Neon',
    background: '#000000',
    primary: '#FF007F',
    secondary: '#00f2fa',
    tertiary: '#FF6B35',
    accent: '#FFD700',
    text: '#FFFFFF',
    border: '#FF007F',
    glow: true,
    textGlow: '#00f2fa',
    primaryGlow: '#FF007F',
    secondaryGlow: '#00f2fa',
    accentGlow: '#FFD700',
  },
  zwartWit: {
    name: 'Wireframe',
    background: '#ffffff',
    primary: '#ffffff',
    secondary: '#000000',
    tertiary: '#000000',
    accent: '#000000',
    text: '#000000',
    border: '#000000',
    glow: false,
    centerCircle: '#ffffff',
    segment1: '#ffffff',
    segment2: '#ffffff',
    segment3: '#ffffff',
    segment4: '#ffffff',
    segment5: '#ffffff',
    segment6: '#ffffff',
    segment7: '#ffffff',
    segment8: '#ffffff',
  },
  style: {
    name: 'Style',
    background: '#ffffff',
    primary: '#ffffff',
    secondary: '#000000',
    tertiary: '#000000',
    accent: '#000000',
    text: '#000000',
    border: '#000000',
    glow: false,
    centerCircle: '#ffffff',
    segment1: '#ffffff',
    segment2: '#ffffff',
    segment3: '#ffffff',
    segment4: '#ffffff',
    segment5: '#ffffff',
    segment6: '#ffffff',
    segment7: '#ffffff',
    segment8: '#ffffff',
  },
};
